### ISSUE TITLE
_tkinter.TclError: **bitmap "icons/unboundbible.ico"** not defined

### ISSUE THREAD

**Issue by topchyan** [vrybant/unboundbible-pe#1]
```
avetik@zavod:~/build/unboundbible-pe/source$ python unboundbible.py 
bibles/rst+.bbl.unbound
bibles/kjv.bbl.unbound
bibles/kjv+.bbl.unbound
bibles/rstw.bbl.unbound
bibles/ubio.bbl.unbound
Traceback (most recent call last):
  File "unboundbible.py", line 20, in <module>
    win.iconbitmap('icons/unboundbible.ico')
  File "/usr/lib/python3.8/tkinter/__init__.py", line 2071, in wm_iconbitmap
    return self.tk.call('wm', 'iconbitmap', self._w, bitmap)
_tkinter.TclError: bitmap "icons/unboundbible.ico" not defined
avetik@zavod:~/build/unboundbible-pe/source$ 

```

**Comment by topchyan** [comment]
According to [this](https://stackoverflow.com/questions/20860325/python-3-tkinter-iconbitmap-error-in-ubuntu), I suppose it needs an @ character in the bitmap parameter. So I tried to show the full path prepended with the @: 

`"win.iconbitmap('@/home/avetik/build/unboundbible-pe/source/icons/unboundbible.ico')"`

but now am getting another error:

`_tkinter.TclError: error reading bitmap file "/home/avetik/build/unboundbible-pe/source/icons/unboundbible.ico"`

So it sees the file, but is unable to read it. 

python --version
Python 3.8.5

**Comment by topchyan** [comment]
I suspect there is an issue with the included unboundbible.ico file which doesn't seem to be readable by other platform tkinter.
When I replaced the call with another stock icon file it no longer shows the error

`win.iconbitmap('@/usr/local/lib/x86_64-linux-gnu/perl/5.28.1/Tk/demos/images/c.icon')`

After changing case for the following files I was able to load the form successfully (text isn't displayed, but left side menu works)

```
saveicon  = PhotoImage(file='icons/save.gif')
cuticon   = PhotoImage(file='icons/cut.gif')
copyicon  = PhotoImage(file='icons/copy.gif')
pasteicon = PhotoImage(file='icons/paste.gif')
undoicon  = PhotoImage(file='icons/undo.gif')
redoicon  = PhotoImage(file='icons/redo.gif')

```

**Comment by vrybant** [comment]
This can be temporary solution:

if os.name == 'nt': win.iconbitmap('icons/unboundbible.ico')
