### ISSUE TITLE
TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by topchyan** [vrybant/unboundbible-pe#3]
Got this error when trying to run the program

>> python3 unboundbible.py 

```
Traceback (most recent call last):
  File "unboundbible.py", line 16, in <module>
    from bible import *
  File "/media/avetik/SdCard/bin/unboundbible-pe/bible.py", line 93, in <module>
    class Bible(Module):
  File "/media/avetik/SdCard/bin/unboundbible-pe/bible.py", line 154, in Bible
    def getTitles(self) -> list[str]:
TypeError: 'type' object is not subscriptable
```

**Comment by vrybant** [comment]
What is your python version?

**Comment by topchyan** [comment]
Python 3.8.10 (default, Mar 15 2022, 12:22:08) [GCC 9.4.0]

**Comment by vrybant** [comment]
You should use minimum Python 3.9

Starting with Python ≥3.9, to annotate a list, we use the list type, followed by []. 

[understanding-type-annotation-python](https://blog.logrocket.com/understanding-type-annotation-python/)

**Comment by vrybant** [comment]
I downgraded python version. You may try it with Python 3.8.

**Comment by topchyan** [comment]
Tried that with the new code, unfortunately still getting the exact same error

**Comment by vrybant** [comment]
ok, python 3.9 is minimal..

**Comment by topchyan** [comment]
Installed python3.10 

Tried and still getting errors like this:
```

Traceback (most recent call last):
  File "/media/avetik/SdCard/bin/unboundbible-pe-main/unboundbible.py", line 79, in <module>
    copyicon = PhotoImage(file='icons/copy.gif')
  File "/usr/lib/python3.10/tkinter/__init__.py", line 4096, in __init__
    Image.__init__(self, 'photo', name, cnf, master, **kw)
  File "/usr/lib/python3.10/tkinter/__init__.py", line 4041, in __init__
    self.tk.call(('image', 'create', imgtype, name,) + options)
_tkinter.TclError: couldn't open "icons/copy.gif": no such file or directory
```

**Comment by topchyan** [comment]
All good. I installed Python 3.10 on Linux Mint and after I re-cloned the code from git the program opened okay.

**Comment by topchyan** [comment]
I don't think the distribution I am currently using (Linux Mint) supports
this version yet, so I have to wait a bit longer.
